### ISSUE TITLE
Compilation errors for marian-server with default boost version in latest stable versions of Debian and Ubuntu

### ISSUE THREAD

**Issue by santhoshtr** [marian-nmt/marian#377]
### Bug description

Version 1.10.0 does not compile with boost 1.74 or above versions. Specifically, marian-server has the compilation errors due to simple-websocket-server incompatibility with latest boost versions.

Latest stable versions of Debian(bullseye) and Ubuntu ships with Boost 1.74. This makes it difficult to use a Marian release with stable linux distros, unless custom boost installation is done, which is not an easy task. Similarly in docker based setups, if images of debian or ubuntu are used, there also, Marian is not compilable with marian-server. An example issue: https://github.com/Helsinki-NLP/Opus-MT/issues/44

### How to reproduce
Compile Marian with latest ubuntu or debian that comes with boost 1.74. A compilation error similar to https://github.com/marian-nmt/marian-dev/issues/796 is happening

### Context
* Marian version: 1.10.0

This issue has been already fixed in https://github.com/marian-nmt/marian-dev/pull/799(Update simple-websocket-server to the latest version). Please backport that to this repo and provide a minor release(bug fix release). Thanks!
