### ISSUE TITLE
Compiling on ubuntu 18.04 with gcc 7.3.0 fails

### ISSUE THREAD

**Issue by obo** [marian-nmt/marian#190]
Hi,

Compiling on:
- Ubuntu 18.04 LTS bionic, 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64
- gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
- CUDA 8.0
fails. Would you please know what is this error? (Marcin mentioned he hasn't yet even tried cuda with g++7.)

```
[ 53%] Built target libcnpy
CMake Error at marian_cuda_generated_prod.cu.o.cmake:203 (message):
  Error generating
  /lnet/troja/work/people/bojar/IBM/season3/jpnmodels2018troja/playground/s.marian.2c9c458f.20180614-1247/marian/build-dll2/src/marian/src/CMakeFiles/marian_cuda.dir/tensors/gpu/./marian_cuda_generated_prod.cu.o


src/marian/src/CMakeFiles/marian_cuda.dir/build.make:84: recipe for target 'src/marian/src/CMakeFiles/marian_cuda.dir/tensors/gpu/marian_cuda_generated_prod.cu.o' failed
make[2]: *** [src/marian/src/CMakeFiles/marian_cuda.dir/tensors/gpu/marian_cuda_generated_prod.cu.o] Error 1
CMake Error at marian_cuda_generated_tensor_operators.cu.o.cmake:203 (message):
  Error generating
  /lnet/troja/work/people/bojar/IBM/season3/jpnmodels2018troja/playground/s.marian.2c9c458f.20180614-1247/marian/build-dll2/src/marian/src/CMakeFiles/marian_cuda.dir/tensors/gpu/./marian_cuda_generated_tensor_operators.cu.o


src/marian/src/CMakeFiles/marian_cuda.dir/build.make:105: recipe for target 'src/marian/src/CMakeFiles/marian_cuda.dir/tensors/gpu/marian_cuda_generated_tensor_operators.cu.o' failed
make[2]: *** [src/marian/src/CMakeFiles/marian_cuda.dir/tensors/gpu/marian_cuda_generated_tensor_operators.cu.o] Error 1
CMake Error at marian_cuda_generated_dropout.cu.o.cmake:203 (message):
  Error generating
  /lnet/troja/work/people/bojar/IBM/season3/jpnmodels2018troja/playground/s.marian.2c9c458f.20180614-1247/marian/build-dll2/src/marian/src/CMakeFiles/marian_cuda.dir/tensors/gpu/./marian_cuda_generated_dropout.cu.o
```

**Comment by emjotde** [comment]
Oh, you are using CUDA 8.0. I'm pretty sure that does not work with g++7. Cuda 9.2 seems to have g++7 support.

**Comment by emjotde** [comment]
According to various searches it seems that CUDA 8.0 limits you to g++5 ? CUDA 9.0 and 9.1 work with g++6, CUDA 9.2 with g++7.

**Comment by obo** [comment]
I confirm that gcc-7 and cuda 9.0 do not work:

/opt/cuda/9.0/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!

I'll let you know which combination will have succeeded for me.

Thanks, O.

----- Original Message -----
> From: "Marcin Junczys-Dowmunt" <notifications@github.com>
> To: "marian-nmt/marian" <marian@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Friday, 15 June, 2018 10:01:58
> Subject: Re: [marian-nmt/marian] Compiling on ubuntu 18.04 with gcc 7.3.0 fails (#190)

> According to various searches it seems that CUDA 8.0 limits you to g++5 ? CUDA
> 9.0 and 9.1 work with g++6, CUDA 9.2 with g++7.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/marian-nmt/marian/issues/190#issuecomment-397545355

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by hieuhoang** [comment]
cuda 9.2 works with ubuntu 18.04 and gcc/boost out of the box

**Comment by obo** [comment]
I am happy to confirm that.
Thanks! O.

----- Original Message -----
> From: "Hieu Hoang" <notifications@github.com>
> To: "marian-nmt" <marian@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Friday, 15 June, 2018 15:53:31
> Subject: Re: [marian-nmt/marian] Compiling on ubuntu 18.04 with gcc 7.3.0 fails (#190)

> cuda 9.2 works with ubuntu 18.04 and gcc/boost out of the box
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/marian-nmt/marian/issues/190#issuecomment-397628180

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by sortiz** [comment]
Another solution to install marian in Ubuntu 18.04

```bash
$ python3 -mvenv venv
$ source venv/bin/activate
$ pip install cmake
$ cd marian
$ mkdir build
$ cmake ..
$ make -j
```

Then the compilation will fail, but you edit the source file causing the fail and fix the `switch` clause inside the function `AVX_MatrixMult8` as follows:

<pre><code>
  switch(num_A_rows & 7) {
    case 7:
      for(int j = 0; j < num_B_rows; j++) {
        const __m512i *B_row = B + j * sse_width;
        __m512i sum1 = _mm512_setzero_si512();
        __m512i sum2 = _mm512_setzero_si512();
        __m512i sum3 = _mm512_setzero_si512();
        __m512i sum4 = _mm512_setzero_si512();
        __m512i sum5 = _mm512_setzero_si512();
        __m512i sum6 = _mm512_setzero_si512();
        __m512i sum7 = _mm512_setzero_si512();
        for(int k = 0; k < sse_width; k++) {
          __m512i b = *(B_row + k);
          __m512i b_positive = _mm512_abs_epi8(b);
          __mmask64 neg_mask = _mm512_test_epi8_mask(b, _mm512_set1_epi8(-128));
          Accum(zeros, *(A1_row + k), b, b_positive, neg_mask, sum1);
          Accum(zeros, *(A2_row + k), b, b_positive, neg_mask, sum2);
          Accum(zeros, *(A3_row + k), b, b_positive, neg_mask, sum3);
          Accum(zeros, *(A4_row + k), b, b_positive, neg_mask, sum4);
          Accum(zeros, *(A5_row + k), b, b_positive, neg_mask, sum5);
          Accum(zeros, *(A6_row + k), b, b_positive, neg_mask, sum6);
          Accum(zeros, *(A7_row + k), b, b_positive, neg_mask, sum7);
        }
        put.Write(C + i * num_B_rows + j, Reduce16to32(sum1, sum2, sum3, sum4));
        put.Write(C + (i + 4) * num_B_rows + j, Reduce16to32(sum5, sum6));
        put.Write(C + (i + 6) * num_B_rows + j, Reduce16to32(sum7));
      }
      <b>[[fallthrough]];</b>
    case 6:
      for(int j = 0; j < num_B_rows; j++) {
        const __m512i *B_row = B + j * sse_width;
        __m512i sum1 = _mm512_setzero_si512();
        __m512i sum2 = _mm512_setzero_si512();
        __m512i sum3 = _mm512_setzero_si512();
        __m512i sum4 = _mm512_setzero_si512();
        __m512i sum5 = _mm512_setzero_si512();
        __m512i sum6 = _mm512_setzero_si512();
        for(int k = 0; k < sse_width; k++) {
          __m512i b = *(B_row + k);
          __m512i b_positive = _mm512_abs_epi8(b);
          __mmask64 neg_mask = _mm512_test_epi8_mask(b, _mm512_set1_epi8(-128));
          Accum(zeros, *(A1_row + k), b, b_positive, neg_mask, sum1);
          Accum(zeros, *(A2_row + k), b, b_positive, neg_mask, sum2);
          Accum(zeros, *(A3_row + k), b, b_positive, neg_mask, sum3);
          Accum(zeros, *(A4_row + k), b, b_positive, neg_mask, sum4);
          Accum(zeros, *(A5_row + k), b, b_positive, neg_mask, sum5);
          Accum(zeros, *(A6_row + k), b, b_positive, neg_mask, sum6);
        }
        put.Write(C + i * num_B_rows + j, Reduce16to32(sum1, sum2, sum3, sum4));
        put.Write(C + (i + 4) * num_B_rows + j, Reduce16to32(sum5, sum6));
      }
     <b>[[fallthrough]];</b>
    case 5:
      for(int j = 0; j < num_B_rows; j++) {
        const __m512i *B_row = B + j * sse_width;
        __m512i sum1 = _mm512_setzero_si512();
        __m512i sum2 = _mm512_setzero_si512();
        __m512i sum3 = _mm512_setzero_si512();
        __m512i sum4 = _mm512_setzero_si512();
        __m512i sum5 = _mm512_setzero_si512();
        for(int k = 0; k < sse_width; k++) {
          __m512i b = *(B_row + k);
          __m512i b_positive = _mm512_abs_epi8(b);
          __mmask64 neg_mask = _mm512_test_epi8_mask(b, _mm512_set1_epi8(-128));
          Accum(zeros, *(A1_row + k), b, b_positive, neg_mask, sum1);
          Accum(zeros, *(A2_row + k), b, b_positive, neg_mask, sum2);
          Accum(zeros, *(A3_row + k), b, b_positive, neg_mask, sum3);
          Accum(zeros, *(A4_row + k), b, b_positive, neg_mask, sum4);
          Accum(zeros, *(A5_row + k), b, b_positive, neg_mask, sum5);
        }
        put.Write(C + i * num_B_rows + j, Reduce16to32(sum1, sum2, sum3, sum4));
        put.Write(C + (i + 4) * num_B_rows + j, Reduce16to32(sum5));
      }
     <b>[[fallthrough]];</b>
    case 4:
      for(int j = 0; j < num_B_rows; j++) {
        const __m512i *B_row = B + j * sse_width;
        __m512i sum1 = _mm512_setzero_si512();
        __m512i sum2 = _mm512_setzero_si512();
        __m512i sum3 = _mm512_setzero_si512();
        __m512i sum4 = _mm512_setzero_si512();
        for(int k = 0; k < sse_width; k++) {
          __m512i b = *(B_row + k);
          __m512i b_positive = _mm512_abs_epi8(b);
          __mmask64 neg_mask = _mm512_test_epi8_mask(b, _mm512_set1_epi8(-128));
          Accum(zeros, *(A1_row + k), b, b_positive, neg_mask, sum1);
          Accum(zeros, *(A2_row + k), b, b_positive, neg_mask, sum2);
          Accum(zeros, *(A3_row + k), b, b_positive, neg_mask, sum3);
          Accum(zeros, *(A4_row + k), b, b_positive, neg_mask, sum4);
        }
        put.Write(C + i * num_B_rows + j, Reduce16to32(sum1, sum2, sum3, sum4));
      }
     <b>[[fallthrough]];</b>
    case 3:
      for(int j = 0; j < num_B_rows; j++) {
        const __m512i *B_row = B + j * sse_width;
        __m512i sum1 = _mm512_setzero_si512();
        __m512i sum2 = _mm512_setzero_si512();
        __m512i sum3 = _mm512_setzero_si512();
        for(int k = 0; k < sse_width; k++) {
          __m512i b = *(B_row + k);
          __m512i b_positive = _mm512_abs_epi8(b);
          __mmask64 neg_mask = _mm512_test_epi8_mask(b, _mm512_set1_epi8(-128));
          Accum(zeros, *(A1_row + k), b, b_positive, neg_mask, sum1);
          Accum(zeros, *(A2_row + k), b, b_positive, neg_mask, sum2);
          Accum(zeros, *(A3_row + k), b, b_positive, neg_mask, sum3);
        }
        put.Write(C + i * num_B_rows + j, Reduce16to32(sum1, sum2));
        put.Write(C + (i + 2) * num_B_rows + j, Reduce16to32(sum3));
      }
     <b>[[fallthrough]];</b>
    case 2:
      for(int j = 0; j < num_B_rows; j++) {
        const __m512i *B_row = B + j * sse_width;
        __m512i sum1 = _mm512_setzero_si512();
        __m512i sum2 = _mm512_setzero_si512();
        for(int k = 0; k < sse_width; k++) {
          __m512i b = *(B_row + k);
          __m512i b_positive = _mm512_abs_epi8(b);
          __mmask64 neg_mask = _mm512_test_epi8_mask(b, _mm512_set1_epi8(-128));
          Accum(zeros, *(A1_row + k), b, b_positive, neg_mask, sum1);
          Accum(zeros, *(A2_row + k), b, b_positive, neg_mask, sum2);
        }
        put.Write(C + i * num_B_rows + j, Reduce16to32(sum1, sum2));
      }
     <b>[[fallthrough]];</b>
    case 1:
      for(int j = 0; j < num_B_rows; j++) {
        const __m512i *B_row = B + j * sse_width;
        __m512i sum1 = _mm512_setzero_si512();
        for(int k = 0; k < sse_width; k++) {
          __m512i b = *(B_row + k);
          __m512i b_positive = _mm512_abs_epi8(b);
          __mmask64 neg_mask = _mm512_test_epi8_mask(b, _mm512_set1_epi8(-128));
          Accum(zeros, *(A1_row + k), b, b_positive, neg_mask, sum1);
        }
        put.Write(C + i * num_B_rows + j, Reduce16to32(sum1));
      }
  }
</code></pre>

Then you do "make" again and that's it.
